/**
 * types.ts — Core TypeScript interfaces for the Nudelball game.
 *
 * All game objects, state, and data structures are defined here
 * so that every module imports from a single source of truth.
 */

/* ===== Primitive / Enum-Like Types ===== */

/** Valid player positions */
export type Position = 'GK' | 'DEF' | 'MID' | 'STR';

/** CSS class suffixes for position badge styling */
export type PositionCSS = 'gk' | 'def' | 'mid' | 'str';

/** Tactic identifiers */
export type TacticId = 'attack' | 'balanced' | 'defensive' | 'counter';

/** Training focus options (simplified: 3 focuses instead of 5) */
export type TrainingFocus = 'balanced' | 'fitness' | 'development';

/** Difficulty levels — easy gives AI handicap and budget boost, hard does the opposite */
export type Difficulty = 'easy' | 'normal' | 'hard';

/** Team strength display modes in settings */
export type StrengthDisplay = 'none' | 'power' | 'avg';

/** Theme modes */
export type Theme = 'dark' | 'light';

/** Supported languages */
export type Language = 'en' | 'pt' | 'es';

/** Transfer log entry types */
export type TransferType = 'buy' | 'sell';

/** Player role specializations (#5) */
export type PlayerRole = 'playmaker' | 'targetMan' | 'ballWinner' | 'speedster' | 'creator' | 'anchor' | null;

/** Manager reputation tiers (#12) */
export type ReputationTier = 'novice' | 'amateur' | 'semiPro' | 'professional' | 'worldClass' | 'legend';

/** Trophy types awarded at season end */
export type TrophyType = 'gold_trophy' | 'silver_trophy' | 'gold_medal' | 'silver_medal';

/** Match event types (used in both quick-sim and animated matches) */
export type MatchEventType = 'goal' | 'yellow' | 'red';

/** Sort mode for squad view */
export type SortMode = 'position' | 'overall';

/* ===== Player ===== */

/** A single player in a team's roster */
export interface Player {
  /** Full name (e.g. "Carlos García") */
  name: string;
  /** Natural position */
  pos: Position;
  /** Base skill rating (1-50) */
  skill: number;
  /** Current stamina percentage (0-100) */
  stamina: number;
  /** Player age in years */
  age: number;
  /** Matches remaining on injury (0 = healthy) */
  injuredFor: number;
  /** Currently assigned tactical position (null = unassigned) */
  assignedPos: Position | null;
  /** Whether this player is selected in the starting 11 */
  selected: boolean;
  /** Consecutive matches spent on the bench (3+ triggers "fresh" bonus) */
  benchStreak: number;
  /** Lifetime goals scored across all seasons */
  careerGoals: number;
  /** Lifetime appearances across all seasons */
  careerApps: number;
  /** Goals scored in the current season */
  seasonGoals: number;
  /** Appearances in the current season */
  seasonApps: number;
  /** Yellow cards received this season */
  seasonYellows: number;
  /** Red cards received this season */
  seasonReds: number;
  /**
   * Current form rating (-3 to +3).
   * Each point adjusts effective OVR by FORM_OVR_PCT (5%).
   */
  form: number;
  /** Consecutive results contributing to current form streak */
  formStreak: number;
  /** Matches remaining on suspension from cards (0 = available) */
  suspendedFor: number;
  /** Whether this player was generated by the youth academy (legacy, always false in v2.1+) */
  isAcademy: boolean;
  /** Player role specialization (#5) — gives bonuses when paired with matching tactics */
  role?: PlayerRole;
  /**
   * Flag set during animated match when a sub enters the pitch.
   * Subs receive a temporary +10% effective rating boost.
   * Cleared after each match — not persisted.
   */
  subbedIn?: boolean;
  /** Whether the player is "On Fire" — form +3 and 3+ recent goals */
  onFire?: boolean;
}

/* ===== Team ===== */

/** Season or cumulative stats for a team */
export interface Stats {
  /** Matches played */
  p: number;
  /** Wins */
  w: number;
  /** Draws */
  d: number;
  /** Losses */
  l: number;
  /** Goals for (scored) */
  gf: number;
  /** Goals against (conceded) */
  ga: number;
  /** Total points (3 per win, 1 per draw) */
  pts: number;
}

/** A trophy/medal earned at the end of a season */
export interface Trophy {
  /** Type of award */
  type: TrophyType;
  /** Season number when the trophy was earned */
  season: number;
}

/** A team in the active league */
export interface Team {
  /** Unique team index (0-based, matches position in G.teams array) */
  id: number;
  /** Display name (e.g. "Barcelona") */
  name: string;
  /** Current division (1-4) */
  div: number;
  /** Primary colour (hex string, e.g. "#ad1519") — used as flag/plate background candidate */
  c1: string;
  /** Secondary colour (hex string) — used as flag/plate text candidate */
  c2: string;
  /** ISO-ish country code for name generation (e.g. "ES", "EN", "BR") */
  country: string;
  /** Full squad roster */
  players: Player[];
  /** Cumulative all-time stats */
  stats: Stats;
  /** Current season stats (reset each new season) */
  seasonStats: Stats;
  /** Collection of trophies/medals earned */
  trophies: Trophy[];
  /** Index into FORMATIONS array — AI's chosen formation (randomised each season) */
  aiFormation: number;
  /** Team morale (-10 to +10) — affects team strength by ±5% (#4) */
  morale?: number;
  /** Rival team IDs for derby matches (#13) */
  rivals?: number[];
}

/** Raw team data used to initialise teams at game start (from TEAMS_DATA constant) */
export interface TeamData {
  name: string;
  div: number;
  c1: string;
  c2: string;
  country: string;
}

/** A team waiting in the pool to enter/re-enter the league (from WAITING_TEAMS_DATA) */
export interface WaitingTeam {
  name: string;
  c1: string;
  c2: string;
  country: string;
}

/* ===== Fixtures & Match Events ===== */

/** A single match event (goal, yellow card, or red card) */
export interface MatchEvent {
  /** Event type */
  type: MatchEventType;
  /** Team that the event belongs to */
  teamId: number;
  /** Minute of the match (1-90) */
  minute: number;
  /** Name of the player who scored (only for 'goal' events) */
  scorer?: string;
  /** Name of the player who received a card (only for 'yellow' / 'red' events) */
  playerName?: string;
  /** Narrative description of the event (generated by match engine) */
  narrative?: string;
}

/** An animated match event — uses 'min' instead of 'minute' */
export interface AnimatedMatchEvent {
  /** Event type */
  type: MatchEventType;
  /** Team that the event belongs to */
  teamId: number;
  /** Minute of the match (1-90) */
  min: number;
  /** Name of the player who scored (only for 'goal' events) */
  scorer?: string;
  /** Name of the player who received a card (only for 'yellow' / 'red' events) */
  playerName?: string;
}

/** Injury record generated after a match */
export interface MatchInjury {
  /** Name of the injured player */
  name: string;
  /** Team ID the player belongs to */
  teamId: number;
  /** Number of matches the player will miss */
  duration: number;
}

/** A single league fixture */
export interface Fixture {
  /** Home team ID */
  home: number;
  /** Away team ID */
  away: number;
  /** Home team goals (null if not yet played) */
  homeGoals: number | null;
  /** Away team goals (null if not yet played) */
  awayGoals: number | null;
  /** Match events (goals, cards) */
  events: MatchEvent[];
  /** Injuries generated after the match (added post-sim) */
  injuries?: MatchInjury[];
  /** Man of the Match player name (set after simulation) */
  motm?: string;
  /** Man of the Match team ID */
  motmTeamId?: number;
}

/**
 * Fixtures are stored by division number, where each division
 * contains an array of rounds (weeks), and each round contains
 * an array of fixtures.
 */
export type FixturesByDivision = Record<number, Fixture[][]>;

/* ===== Formation & Tactics ===== */

/** Formation slot counts by position */
export interface FormationSlots {
  GK: number;
  DEF: number;
  MID: number;
  STR: number;
}

/** A formation definition (e.g. "4-4-2") */
export interface Formation {
  /** Display label (e.g. "4-4-2") */
  label: string;
  /** Number of players per position */
  slots: FormationSlots;
}

/** Tactic configuration affecting match simulation */
export interface Tactic {
  /** Expected goals multiplier when playing at home */
  homeBonus: number;
  /** Expected goals multiplier when playing away */
  awayBonus: number;
  /** Multiplied against opponent's expected goals (lower = better defence) */
  defPenalty: number;
  /** Human-readable label */
  label: string;
  /** Emoji icon displayed in the UI */
  icon: string;
}

/* ===== Transfer Market ===== */

/** A free agent available for signing */
export interface FreeAgent {
  /** Player name */
  name: string;
  /** Natural position */
  pos: Position;
  /** Base skill rating (1-50) */
  skill: number;
  /** Current stamina (always 100 for free agents) */
  stamina: number;
  /** Consecutive bench appearances (always 0 for free agents) */
  benchStreak: number;
  /** Assigned position (always null for free agents) */
  assignedPos: null;
  /** Selection state (always false for free agents) */
  selected: false;
  /** Player age */
  age: number;
  /** Calculated market value in currency units */
  marketValue: number;
}

/** Entry in the transfer log tracking buys and sells */
export interface TransferLogEntry {
  /** Season when the transfer occurred */
  season: number;
  /** Whether the player was bought or sold */
  type: TransferType;
  /** Name of the player transferred */
  playerName: string;
  /** ID of the team involved */
  teamId: number;
  /** Name of the team involved */
  teamName: string;
  /** Transfer fee (0 for free signings) */
  amount: number;
}

/* ===== Top Scorers ===== */

/** An entry in the top scorers table, keyed by "teamId_playerName" */
export interface TopScorerEntry {
  /** Player name */
  name: string;
  /** Team ID the player belongs to */
  teamId: number;
  /** Goals scored this season */
  goals: number;
}

/** Top scorers dictionary — key format: "{teamId}_{playerName}" */
export type TopScorers = Record<string, TopScorerEntry>;

/* ===== Season History ===== */

/** Reference to a team in season history (by name) */
export interface HistoryTeamRef {
  name: string;
  teamId?: number;
}

/** Reference to a top scorer in season history */
export interface HistoryTopScorer {
  name: string;
  teamName: string;
  teamId: number;
  goals: number;
}

/** A completed season's summary for the history view */
export interface SeasonHistory {
  /** Season number */
  season: number;
  /** Division 1 champion */
  div1Champion: HistoryTeamRef | null;
  /** Division 1 runner-up */
  div1RunnerUp: HistoryTeamRef | null;
  /** Division 2 champion */
  div2Champion: HistoryTeamRef | null;
  /** Division 2 runner-up */
  div2RunnerUp: HistoryTeamRef | null;
  /** Season's overall top scorer */
  topScorer: HistoryTopScorer | null;
}

/* ===== Records (Trophy Room) ===== */

/** A single stat record (value + season when achieved) */
export interface StatRecord {
  value: number;
  season: number;
}

/** A league-wide stat record (includes team name) */
export interface LeagueStatRecord {
  value: number;
  season: number;
  team: string;
}

/** Record for the top scorer in a single season */
export interface TopScorerRecord {
  name: string;
  goals: number;
  season: number;
}

/** League-wide top scorer record */
export interface LeagueTopScorerRecord {
  name: string;
  goals: number;
  season: number;
  team: string;
}

/** Record for biggest win/defeat */
export interface MatchResultRecord {
  score: string;
  opponent: string;
  season: number;
  diff: number;
}

/** League-wide match result record */
export interface LeagueMatchResultRecord {
  score: string;
  team: string;
  opponent: string;
  season: number;
  diff: number;
}

/** Record for most goals in a single match */
export interface MostGoalsRecord {
  score: string;
  opponent: string;
  season: number;
  total: number;
}

/** League-wide most goals in a match record */
export interface LeagueMostGoalsRecord {
  score: string;
  team: string;
  opponent: string;
  season: number;
  total: number;
}

/** League-wide records (any team, any season) */
export interface LeagueRecords {
  bestPts: LeagueStatRecord;
  bestWins: LeagueStatRecord;
  fewestDefeats: LeagueStatRecord;
  bestAttack: LeagueStatRecord;
  bestDefence: LeagueStatRecord;
  bestGD: LeagueStatRecord;
  topScorerSeason: LeagueTopScorerRecord;
  biggestWin: LeagueMatchResultRecord;
  biggestDefeat: LeagueMatchResultRecord;
  mostGoalsMatch: LeagueMostGoalsRecord;
  highestPower: LeagueStatRecord;
}

/** Full Trophy Room records object */
export interface Records {
  /* --- Player single-season personal bests --- */
  bestPts: StatRecord;
  bestWins: StatRecord;
  fewestDefeats: StatRecord;
  bestAttack: StatRecord;
  bestDefence: StatRecord;
  bestGD: StatRecord;
  topScorerSeason: TopScorerRecord;
  biggestWin: MatchResultRecord;
  biggestDefeat: MatchResultRecord;
  mostGoalsMatch: MostGoalsRecord;
  highestPower: StatRecord;

  /* --- League-wide records --- */
  league: LeagueRecords;

  /* --- Milestones --- */
  highestDiv: number;
  totalPromotions: number;
  totalRelegations: number;
  consecutiveDiv1: number;
  maxConsecutiveDiv1: number;
  currentUnbeaten: number;
  longestUnbeaten: number;
  currentWinStreak: number;
  longestWinStreak: number;
  totalCleanSheets: number;

  /* --- Hall of Fame: persistent player goal tracking --- */
  /** Maps player name to their total career goals */
  hallOfFame: Record<string, number>;
}

/* ===== Settings ===== */

/** Persistent user settings (saved to localStorage independently of game state) */
export interface Settings {
  /** UI colour theme */
  theme: Theme;
  /** Display language */
  lang: Language;
  /** How team strength is shown in the UI */
  strengthDisplay: StrengthDisplay;
  /** Sound effect volume (0.0 - 1.0) */
  volume: number;
  /** Whether sound is muted */
  muted: boolean;
  /** Game difficulty level (new in modular version) */
  difficulty?: Difficulty;
}

/* ===== Save Slots (Multi-Save Feature) ===== */

/** A save slot for the multi-save feature */
export interface SaveSlot {
  /** Unique slot identifier */
  id: string;
  /** User-assigned name for this save (e.g. "Barcelona Run") */
  name: string;
  /** ISO timestamp of when the save was last updated */
  timestamp: string;
  /** Serialised game state */
  data: GameState;
}

/* ===== Player Profile View ===== */

/** Identifies which player profile is being viewed */
export interface ViewingPlayerId {
  teamId: number;
  playerIdx: number;
}

/* ===== Full Game State ===== */

/**
 * The master game state object — the single source of truth for
 * all mutable game data. Serialised to localStorage for saves.
 */
export interface GameState {
  /** Manager name entered at game start */
  manager: string;
  /** ID of the human player's team (null before selection) */
  playerTeamId: number | null;
  /** Current season number (1-based) */
  season: number;
  /** Current week within the season (1-based, up to TOTAL_SEASON_WEEKS) */
  week: number;
  /** All teams in the league */
  teams: Team[];
  /** League fixtures grouped by division and round */
  fixtures: FixturesByDivision;

  /* --- Waiting / Return Pools (promotion/relegation rotation) --- */
  /** Teams waiting to enter the league (from WAITING_TEAMS_DATA) */
  waitingPool: WaitingTeam[];
  /** Teams that were relegated out, waiting to return after 2 seasons */
  returnPool: Array<WaitingTeam & { returnIn?: number }>;

  /* --- UI State --- */
  /** Whether squad list is sorted by position (true) or overall (false) */
  sortByPos: boolean;
  /** Whether an animated match is currently in progress */
  matchInProgress: boolean;
  /** Currently selected division tab on the Table view */
  tableDivTab: number;
  /** Currently selected division tab on the Calendar view */
  calDivTab: number;
  /** Currently selected division tab on the Scorers view (0 = all) */
  scorersDivTab: number;

  /* --- Scoring --- */
  /** Season top scorers dictionary */
  topScorers: TopScorers;

  /* --- History --- */
  /** Completed season summaries */
  seasonHistory: SeasonHistory[];

  /* --- Transfer Market --- */
  /** Available free agents for signing */
  freeAgents: FreeAgent[];
  /** Team budgets — key is team ID */
  budgets: Record<number, number>;
  /** Whether the transfer window is currently open */
  transferWindow: boolean;
  /** Whether the week-1 transfer reminder has been shown */
  transferReminderShown?: boolean;
  /** Log of transfers made this season */
  transferLog: TransferLogEntry[];
  /** Whether the one-time free first signing has been used */
  usedFreeSign?: boolean;

  /* --- Trophy Room --- */
  /** All-time and season records for Trophy Room */
  records: Records | null;

  /* --- Formation --- */
  /** Index into FORMATIONS for the human player's auto-pick formation */
  selectedFormationIdx: number;

  /* --- Tactics & Training (v2.0) --- */
  /** Currently selected match tactic */
  tactic: TacticId;
  /** Currently selected training focus */
  trainingFocus: TrainingFocus;

  /* --- Animated Match State (transient, not persisted meaningfully) --- */
  /** Number of substitutions used in the current animated match */
  matchSubs: number;
  /** Indices of players sent off by red card in the current animated match */
  matchRedCards: number[];

  /* --- Player Profile --- */
  /** Identifies the player profile currently being viewed */
  viewingPlayerId: ViewingPlayerId | null;

  /* --- v3.0 Features --- */

  /** Stadium facilities (#7) */
  facilities?: Facilities;
  /** Active sponsorship deal (#6) */
  sponsorship?: Sponsorship | null;
  /** Players on loan (#8) */
  loans?: LoanPlayer[];
  /** Youth prospects available for promotion (#14) */
  youthProspects?: YouthProspect[];
  /** Squad auto-rotation rules (#19) */
  squadRules?: SquadRules;
  /** Scout network level (#18): 0=basic, 1=all divs, 2=hidden gems */
  scoutLevel?: ScoutLevel;
  /** Active negotiation state (#17) */
  negotiation?: NegotiationState | null;

  /* --- Season Recap Gate (v3.1) --- */

  /** Pending season recap data — shown in dashboard before new season can start */
  seasonRecapData?: SeasonRecapData | null;
}

/* ===== Season Recap Data ===== */

/**
 * Stored after endOfSeason() runs, before the new season starts.
 * The dashboard renders this inline as a mandatory recap gate.
 * Cleared when the player clicks "Start Next Season".
 */
export interface SeasonRecapData {
  /** The season that just completed */
  season: number;
  /** Promotion/relegation moves (stored by ID since team.div has changed) */
  moves: Array<{ teamId: number; type: string; from: number; to: number }>;
  /** Financial awards distributed */
  financialAwards: Array<{ teamId: number; type: string; amount: number }>;
  /** Total cash earned by the player this season */
  playerTotalCash: number;
}

/* ===== Difficulty Settings ===== */

/** Multipliers applied based on difficulty level */
export interface DifficultyMultipliers {
  /** Multiplier applied to AI team strength */
  aiStrengthMult: number;
  /** Multiplier applied to the human player's budget */
  budgetMult: number;
  /** Multiplier applied to training success chance */
  trainingMult: number;
}

/* ===== Development Curves ===== */

/** Constants governing player skill growth and decline by age (simplified) */
export interface DevelopmentCurveConfig {
  /** Age at which peak performance begins */
  peakAgeStart: number;
  /** Age at which peak performance ends */
  peakAgeEnd: number;
  /** Extra training success chance per year below peak age */
  youngBonus: number;
  /** Chance of skill decline per year above peak end */
  declineRate: number;
  /** Age at which players retire */
  retirementAge: number;
}

/**
 * A single age-band entry in the development curve table.
 * Used by config/index.ts to define improvement/decline probabilities
 * per age bracket.
 */
export interface DevelopmentCurve {
  /** Lower bound of the age range (inclusive) */
  minAge: number;
  /** Upper bound of the age range (inclusive) */
  maxAge: number;
  /** Probability (0-1) of gaining skill in this age bracket */
  improvementChance: number;
  /** Maximum skill points that can be gained per season */
  maxGain: number;
  /** Probability (0-1) of losing skill in this age bracket */
  declineChance: number;
  /** Maximum skill points that can be lost per season */
  maxLoss: number;
}

/* ===== Country Names ===== */

/** Name pool for a single country */
export interface CountryNamePool {
  first: string[];
  last: string[];
}

/**
 * Alias for CountryNamePool — used by data/teams.ts.
 * Both names refer to the same shape: { first: string[], last: string[] }.
 */
export type NamePool = CountryNamePool;

/**
 * Two-letter country codes used across the game for name generation
 * and flag display. Matches the keys in COUNTRY_NAMES.
 */
export type CountryCode =
  | 'ES' | 'EN' | 'PT' | 'DE' | 'FR' | 'BR' | 'US' | 'CA'
  | 'UA' | 'PL' | 'JP' | 'CN' | 'AD' | 'FK' | 'AR' | 'CO'
  | 'CL' | 'NL' | 'HR' | 'TR' | 'SE' | 'KR' | 'EG' | 'UY'
  | 'AU' | 'IL' | 'IT';

/** All country name pools, keyed by country code */
export type CountryNames = Record<string, CountryNamePool>;

/* ===== Changelog ===== */

/** A single version entry in the changelog */
export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  changes: string[];
}

/* ===== Division Range ===== */

/** Skill range for a division — [minSkill, maxSkill] */
export type DivisionRange = [number, number];

/* ===== Prize Money ===== */

/** Prize money configuration */
export interface PrizeMoney {
  div1Champion: number;
  div1RunnerUp: number;
  promotionBonus: number;
  avoidRelegation: number;
  relegation: number;
}

/* ===== Solidarity Payment ===== */

/** Solidarity payment range */
export interface SolidarityPayment {
  min: number;
  max: number;
}

/* ===== Partial Player (for makePlayer extra param) ===== */

/** Extra fields that can be merged when creating a player via `makePlayer()` */
export type PlayerExtra = Partial<Player>;

/* ===== Power Levels ===== */

/** Breakdown of team power by position group */
export interface PowerLevels {
  GK: number;
  DEF: number;
  MID: number;
  STR: number;
  total: number;
}

/* ===== Match Simulation Options ===== */

/** Options passed to the match simulation engine */
export interface MatchSimOptions {
  /** Tactic override for the player's team */
  tacticOverride?: TacticId;
  /** Difficulty multiplier applied to AI team strength (default 1.0) */
  difficulty?: number;
}

/* ===== Season-End Types ===== */

/** A promotion/relegation/entry/exit move at season end */
export interface SeasonMove {
  team: Team;
  from: number;
  to: number;
  type: 'promote' | 'relegate' | 'out' | 'enter';
}

/** A trophy/award given at season end */
export interface SeasonAward {
  team: Team;
  award: TrophyType;
}

/** A financial award at season end */
export interface FinancialAward {
  team: Team;
  type: 'champion' | 'runnerUp' | 'promotion' | 'avoidRelegation' | 'relegation' | 'parachute' | 'solidarityPaid' | 'solidarityReceived';
  amount: number;
}

/* ===== Return Pool Team ===== */

/** A team that has been relegated out and may return after a cooldown period */
export interface ReturnPoolTeam {
  name: string;
  c1: string;
  c2: string;
  country: string;
  /** Season number when the team is eligible to return */
  returnSeason: number;
  stats?: Stats;
  trophies?: Trophy[];
}

/* ===== AI Player For Sale (inter-team transfers) ===== */

/** A player available for purchase from an AI team */
export interface AIPlayerForSale {
  /** Index in the AI team's players array */
  playerIdx: number;
  /** The player data */
  player: Player;
  /** The asking price */
  price: number;
}

/* ===== Stadium Facilities (#7) ===== */

/** Stadium facility upgrade levels (0-3) */
export interface Facilities {
  /** Training facility level — boosts training effectiveness */
  trainingFacility: number;
  /** Youth academy level — regens start with bonus skill */
  youthAcademy: number;
  /** Stadium level — increases base season income */
  stadium: number;
}

/* ===== Sponsorship Deals (#6) ===== */

/** An active sponsorship contract */
export interface Sponsorship {
  /** Sponsor tier: 'small' | 'medium' | 'large' */
  tier: string;
  /** Income per season in dollars */
  incomePerSeason: number;
  /** Minimum division required to keep this sponsor */
  requiredDiv: number;
}

/* ===== Loan System (#8) ===== */

/** A player on loan for the current season */
export interface LoanPlayer {
  /** The loaned player */
  player: Player;
  /** Team ID the player is loaned from */
  fromTeamId: number;
  /** Fee paid for the loan */
  loanFee: number;
}

/* ===== Youth Academy Pipeline (#14) ===== */

/** A youth prospect available for promotion */
export interface YouthProspect {
  /** The prospect's player data */
  player: Player;
  /** Whether the prospect has been promoted to first team */
  promoted: boolean;
}

/* ===== Squad Rules / Auto-Rotation (#19) ===== */

/** Rules for automatic squad rotation */
export interface SquadRules {
  /** Rest players below this stamina threshold (null = disabled) */
  restBelowStamina: number | null;
  /** Always start highest-skill players */
  alwaysStartBest: boolean;
}

/* ===== Scout Network (#18) ===== */

/** Scout upgrade levels */
export type ScoutLevel = 0 | 1 | 2;

/* ===== Transfer Negotiation (#17) ===== */

/** State of an ongoing negotiation */
export interface NegotiationState {
  /** Seller team ID */
  sellerTeamId: number;
  /** Player index in seller's roster */
  playerIdx: number;
  /** Current asking price */
  askingPrice: number;
  /** Minimum price the seller will accept */
  minimumPrice: number;
  /** Rounds of negotiation remaining */
  roundsLeft: number;
}

/* ===== Season Awards (#15) ===== */

/** An individual season award */
export interface SeasonAwardEntry {
  /** Award type */
  type: 'mvp' | 'goldenBoot' | 'bestYoung' | 'playerOfSeason';
  /** Player name */
  playerName: string;
  /** Team name */
  teamName: string;
  /** Extra info (goals, rating, etc.) */
  value: number;
}
